### ISSUE TITLE
ERROR installing uceasy

### ISSUE THREAD

**Issue by RominaSSBatista** [uceasy/uceasy#5]
Hi @caioraposo, I am following your [tutorial](url) on github to install uceasy. Unfortunatly I was not be able to complete since I got the following ERROR:

``(phyluce) [romina.batista2@sdumont14 ~]$ pip install uceasy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting uceasy
  ERROR: Could not find a version that satisfies the requirement uceasy (from versions: none)
ERROR: No matching distribution found for uceasy``

Could you please give me a hand on it? 

1. It could be python version? 
2. Is it necessary call python version3 first, before run the cmmdline ``pip install uceasy``

Many thanks for your help!

**Comment by RominaSSBatista** [comment]
Hi @caioraposo, I just figured out the user needs to have python 3 or higher to get ``pip install uceasy`` running smoothing. I strongly recommend making it clear on the documentation.

**Comment by caioraposo** [comment]
Sure, I'll make that clear
