### ISSUE TITLE
ERROR downloading the tutorial

### ISSUE THREAD

**Issue by RominaSSBatista** [uceasy/uceasy#6]
Hi @caioraposo, I am getting the following ERROR trying to run your tutorial:

``(phyluce) [romina.batista2@sdumont14 uceasy-tutorial]$ tar -xfv tutorial.tar.gz 
tar: v: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now``

How can I solve it?

**Comment by caioraposo** [comment]
Try running tar without the v flag, like this.
```
tar -xf tutorial.tar.gz
```
I'll fix that in a sec.
