### ISSUE TITLE
flag -h

### ISSUE THREAD

**Issue by RominaSSBatista** [uceasy/uceasy#7]
Based on this page https://github.com/uceasy/uceasy/wiki/Running-UCEasy 
the following command is not working @caioraposo 
$ uceasy -h

But this is working fine 
$ uceasy --help

**Comment by caioraposo** [comment]
For me both are working, are you using the last version? (0.2.3)
But it should work in previous versions as well

**Comment by RominaSSBatista** [comment]
@caioraposo if I install uceasy via 

pip3 install uceasy 

it Successfully installed uceasy-1.0.1

**Comment by RominaSSBatista** [comment]
Rominas-MacBook-Pro-10:uceasy-tutorial $ uceasy -h
Usage: uceasy [OPTIONS]
Try 'uceasy --help' for help.

Error: no such option: -h

**Comment by caioraposo** [comment]
Oh I see, this is a really old release which was still available at PyPI.
I removed it and it should work properly now, try installing with this command:
```pip3 install uceasy==0.2.3```

**Comment by caioraposo** [comment]
If you get a message like "uceasy already installed" just uninstall with this command: ```pip3 uninstall uceasy```

**Comment by RominaSSBatista** [comment]
Awesome! It is now working properly. 

I 1st run the command: 
`pip3 uninstall uceasy`

and then 

`pip3 install uceasy`

Finally: 

`uceasy -h`

I will close it for now. 
Thanks!!!
